name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a3

      - name: Install apt dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libhdf5-serial-dev hdf5-tools pkg-config

      - name: Install homebrew dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install hdf5 pkg-config

      - name: Install h5py
        run: |
          pip install h5py

      - name: Install pip dependencies
        run: |
          pip install wheel
          pip install Cython
          pip install -r requirements.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        #run: python setup.py sdist bdist_wheel
        # to supply options, put them in 'env', like:
        env:
          #CIBW_BEFORE_ALL_LINUX: apt-get install -y libhdf5-serial-dev hdf5-tools pkg-config
          #CIBW_ARCHS_LINUX: "x86_64"
          #CIBW_MANYLINUX_X86_64_IMAGE: manylinux2_24
          #CIBW_BEFORE_ALL_LINUX: yum install -y hdf5-devel pkgconfig
          CIBW_BEFORE_ALL_LINUX: yum install -y pkgconfig; .github/workflows/install_hdf5.sh
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
