name: Build bitshuffle wheels

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        hdf5: [1.8.11, 1.10.7]

    steps:
      # Checkout bitshuffle
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a3

      # Build wheels for linux and x86 platforms
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse-hdf5-${{ matrix.hdf5 }}
        env:
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BEFORE_ALL_LINUX: chmod +x .github/workflows/install_hdf5.sh; .github/workflows/install_hdf5.sh ${{ matrix.hdf5 }}
          CIBW_ENVIRONMENT: "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib"
          CIBW_TEST_REQUIRES: pytest
          # Run units tests but disable test_h5plugin.py
          CIBW_TEST_COMMAND: CI_BUILD_WHEEL=1 pytest {package}/tests

      # Package wheels and host on CI
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse-hdf5-${{ matrix.hdf5 }}/*.whl
